### ISSUE TITLE
1.15 update? + Suggestion

### ISSUE THREAD

**Issue by SirUmnei** [PrinceOfAmber/DecoLayers#4]
Hey! Just wanted to know if you plan to update the mod into 1.15.2? If you do, I also have a suggestion!

Perhaps it would be possible to add these layers into world generation much like snow naturally generates on snow biomes, to give terrain just that much more depth. It would mostly affects biomes with grass, sand and gravel like terrain, leaving some of the other stuff for the player to craft. I wanted this simply because I use TerraForged to generate the world, and the snow biomes look just gorgeous with a smooth layer of snow going up their hills, and having other biomes look just as smooth would be simply amazing. Not sure if this would be possible at all, but it's a suggestion nothenless.

Hope you do update! Thank you for your work, regardless of your answer! :D

**Comment by Lothrazar** [comment]
Adding the blocks into world generation is a great idea, but thats a whole extra layer of complexity.

1.15 update is out.  And actually since world gen is changing so much in 1.16, i will look into it then.   ALso, it sounds like in 1.16.2 we will be able to change worldgen with data packs so ill keep it in mind 

:)
